/*
 * Copyright (c) 2026; see AUTHORS file.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.yellowstonegames.world;

import com.github.tommyettinger.random.AceRandom;
import com.github.tommyettinger.random.EnhancedRandom;
import com.github.yellowstonegames.core.DescriptiveColor;
import com.github.yellowstonegames.core.annotations.Beta;
import com.github.yellowstonegames.place.Biome;
import com.github.yellowstonegames.text.Language;

/**
 * Generates alien planet {@link Biome} tables for a {@link BiomeMapper} to use. This currently only works with
 * {@link com.github.yellowstonegames.world.BiomeMapper.BlendedBiomeMapper}, which is usually the best choice anyway.
 * This allows you to generate biome tables with arbitrary colors for oceans, vegetation (or life in general), and
 * barren land. It also lets you adjust the amounts of liquid (oceans and lakes) and life on the planet, both relative
 * to barren land. You can also just throw a random number generator at this and get completely generated colors,
 * amounts, and names for biomes in a randomly generated language.
 */
@Beta
public class AlienBiomes {
    /**
     * Creates a new Biome table with 66 items, using a mix of randomly selected colors with random liquid and life
     * levels. Biomes will have gibberish (alien) names generated by a random Language for namer, using random as an
     * option to seed all other generation. If random is null, a randomly-seeded AceRandom is used.
     * <br>
     * This delegates to {@link #generateAlienBiomeTable(EnhancedRandom, Language, int, int, int, int, int)},
     * with the language generated by {@link Language#randomLanguage(EnhancedRandom)}, liquidAmount set to a random int
     * between 0 and 5 inclusive, lifeAmount set to a random int between 0 and 10 inclusive (biased toward lower
     * values), and each color randomly selected.
     * <br>
     * This chooses colors differently for liquid, barren land, and life-covered land. Each has a completely random hue,
     * but liquid is mid-lightness and mid-saturation, barren land is usually darker and less saturated, and life is
     * more saturated and usually lighter.
     *
     * @param random any EnhancedRandom used for all parameters; if null, a randomly-seeded AceRandom will be used
     * @return a new Biome array with gibberish names for biomes that match the 66 expected by {@link BiomeMapper}
     */
    public static Biome[] generateAlienBiomeTable(EnhancedRandom random) {
        if(random == null) random = new AceRandom();
        return generateAlienBiomeTable(random, Language.randomLanguage(random),
                random.nextInt(6), random.minIntOf(0, 11, 3),
                DescriptiveColor.oklabByHSL(random.nextFloat(), random.nextFloat(0.3f, 0.9f), random.nextFloat(0.3f, 0.7f), 1f),
                DescriptiveColor.oklabByHSL(random.nextFloat(), random.nextFloat(0.0f, 0.6f), random.nextFloat(0.1f, 0.7f), 1f),
                DescriptiveColor.oklabByHSL(random.nextFloat(), random.nextFloat(0.6f, 1.0f), random.nextFloat(0.4f, 0.8f), 1f)
        );
    }
    /**
     * Creates a new Biome table with 66 items, using a mix of randomly selected colors with the given liquid and life
     * levels. Biomes will have gibberish (alien) names generated by the given Language for namer, using random as an
     * option to seed all other generation. If random is null, a randomly-seeded AceRandom is used.
     * <br>
     * This delegates to {@link #generateAlienBiomeTable(EnhancedRandom, Language, int, int, int, int, int)},
     * with each color randomly selected by {@code random}.
     * <br>
     * This chooses colors differently for liquid, barren land, and life-covered land. Each has a completely random hue,
     * but liquid is mid-lightness and mid-saturation, barren land is usually darker and less saturated, and life is
     * more saturated and usually lighter.
     * <br>
     * This lets you specify a {@link Language} to generate Biome names with. You may want to remove accents from any
     * generated Language to make sure it can print in an arbitrary font; use {@link Language#removeAccents()} for this.
     * Or, select an existing ASCII-only language, like {@link Language#HLETKIP} or {@link Language#DEEP_SPEECH}.
     *
     * @param random any EnhancedRandom used for all parameters; if null, a randomly-seeded AceRandom will be used
     * @param namer a Language to generate gibberish names for biomes
     * @param liquidAmount between 0 (totally dry) and 5 (very wet)
     * @param lifeAmount between 0 and about 10 (with 5 being a typical Earth-like planet)
     * @return a new Biome array with gibberish names for biomes that match the 66 expected by {@link BiomeMapper}
     */
    public static Biome[] generateAlienBiomeTable(EnhancedRandom random, Language namer,
                                                  int liquidAmount, int lifeAmount) {
        if(random == null) random = new AceRandom();
        return generateAlienBiomeTable(random, namer, liquidAmount, lifeAmount,
                DescriptiveColor.oklabByHSL(random.nextFloat(), random.nextFloat(0.3f, 0.9f), random.nextFloat(0.3f, 0.7f), 1f),
                DescriptiveColor.oklabByHSL(random.nextFloat(), random.nextFloat(0.0f, 0.6f), random.nextFloat(0.1f, 0.7f), 1f),
                DescriptiveColor.oklabByHSL(random.nextFloat(), random.nextFloat(0.6f, 1.0f), random.nextFloat(0.4f, 0.8f), 1f)
        );
    }

    /**
     * Creates a new Biome table with 66 items, using a mix of the given Oklab colors that depends on the given
     * liquidAmount and lifeAmount. Biomes will have gibberish (alien) names generated by namer, using random as an
     * option to seed the Biome name generation. The EnhancedRandom is not used for anything else.
     * <br>
     * This delegates to {@link #generateAlienBiomeTable(EnhancedRandom, Language, int, int, int, int, int)},
     * with lifeAmount set to 5.
     * <br>
     * This lets you specify a {@link Language} to generate Biome names with. You may want to remove accents from any
     * generated Language to make sure it can print in an arbitrary font; use {@link Language#removeAccents()} for this.
     * Or, select an existing ASCII-only language, like {@link Language#HLETKIP} or {@link Language#DEEP_SPEECH}.
     *
     * @param random any EnhancedRandom used for Biome names; if null, a randomly-seeded AceRandom will be used
     * @param namer a Language to generate gibberish names for biomes
     * @param liquidAmount between 0 (totally dry) and 5 (very wet)
     * @param liquidColorOklab an Oklab packed int for liquids on the planet, as produced by {@link DescriptiveColor}
     * @param barrenColorOklab an Oklab packed int for barren surfaces, as produced by {@link DescriptiveColor}
     * @param lifeColorOklab an Oklab packed int for vegetation on the planet, as produced by {@link DescriptiveColor}
     * @return a new Biome array with gibberish names for biomes that match the 66 expected by {@link BiomeMapper}
     */
    public static Biome[] generateAlienBiomeTable(EnhancedRandom random, Language namer, int liquidAmount,
                                                  int liquidColorOklab, int barrenColorOklab, int lifeColorOklab) {
        return generateAlienBiomeTable(random, namer, liquidAmount, 5, liquidColorOklab, barrenColorOklab, lifeColorOklab);

    }

    /**
     * Creates a new Biome table with 66 items, using a mix of the given Oklab colors that depends on the given
     * liquidAmount and lifeAmount. Biomes will have gibberish (alien) names generated by namer, using random as an
     * option to seed the Biome name generation. The EnhancedRandom is not used for anything else.
     * <br>
     * This lets you specify a {@link Language} to generate Biome names with. You may want to remove accents from any
     * generated Language to make sure it can print in an arbitrary font; use {@link Language#removeAccents()} for this.
     * Or, select an existing ASCII-only language, like {@link Language#HLETKIP} or {@link Language#DEEP_SPEECH}.
     *
     * @param random any EnhancedRandom used for Biome names; if null, a randomly-seeded AceRandom will be used
     * @param namer a Language to generate gibberish names for biomes
     * @param liquidAmount between 0 (totally dry) and 5 (very wet)
     * @param lifeAmount between 0 and about 10 (with 5 being a typical Earth-like planet)
     * @param liquidColorOklab an Oklab packed int for liquids on the planet, as produced by {@link DescriptiveColor}
     * @param barrenColorOklab an Oklab packed int for barren surfaces, as produced by {@link DescriptiveColor}
     * @param lifeColorOklab an Oklab packed int for vegetation on the planet, as produced by {@link DescriptiveColor}
     * @return a new Biome array with gibberish names for biomes that match the 66 expected by {@link BiomeMapper}
     */
    public static Biome[] generateAlienBiomeTable(EnhancedRandom random, Language namer,
                                                  int liquidAmount, int lifeAmount,
                                                  int liquidColorOklab, int barrenColorOklab, int lifeColorOklab) {
        if(random == null) random = new AceRandom();
        Biome[] table = new Biome[66];
        System.arraycopy(Biome.TABLE, 60, table, 60, 6);
        switch (liquidAmount){
            case 0: {
                String coldDesert = namer.word(random, true);
                for (int m = 0; m < 6; m++) {
                    int h = 0;
                    int i = m * 6 + h;
                    table[i] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.ALL[m], coldDesert, DescriptiveColor.unevenMix(barrenColorOklab, 30, liquidColorOklab, m + 1));
                }
                String coldLowlands = namer.word(random, true);
                for (int i = 36, m = 6; i < 60; i += 6, m++) {
                    table[i] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.ALL[m], coldLowlands, DescriptiveColor.unevenMix(barrenColorOklab, 30, DescriptiveColor.BLACK, m));
                }
                String hotDesert = namer.word(random, true);
                for (int m = 0; m < 6; m++) {
                    for (int h = 1; h < 6; h++) {
                        int i = m * 6 + h;
                        table[i] = new Biome(Biome.Heat.ALL[h], Biome.Moisture.ALL[m], hotDesert, DescriptiveColor.unevenMix(barrenColorOklab, 30, liquidColorOklab, m + 1, DescriptiveColor.ORANGE, h + 1));
                    }
                }
                String hotLowlands = namer.word(random, true);
                for (int m = 6; m < 10; m++) {
                    for (int h = 1; h < 6; h++) {
                        int i = m * 6 + h;
                        table[i] = new Biome(Biome.Heat.ALL[h], Biome.Moisture.ALL[m], hotLowlands, DescriptiveColor.unevenMix(barrenColorOklab, 30, DescriptiveColor.BLACK, m, DescriptiveColor.ORANGE, h + 1));

                    }
                }
                break;
            }
            case 1:
            case 2:
            case 3:
            case 4:
            case 5: {
                String coldDesert = namer.word(random, true);
                for (int m = 0; m < 6 - liquidAmount; m++) {
                    int h = 0;
                    int i = m * 6 + h;
                    table[i] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.ALL[m], coldDesert, DescriptiveColor.unevenMix(barrenColorOklab, 30, liquidColorOklab, m + 1, DescriptiveColor.WHITE, m));
                }
                if(lifeAmount <= 0) {
                    for (int m = 6 - liquidAmount; m < 6; m++) {
                        int h = 0;
                        int i = m * 6 + h;
                        table[i] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.ALL[m], namer.word(random, true), DescriptiveColor.unevenMix(barrenColorOklab, 5, liquidColorOklab, m + 1, DescriptiveColor.BLACK, m));
                    }
                } else {
                    for (int m = 6 - liquidAmount; m < 6; m++) {
                        int h = 0;
                        int i = m * 6 + h;
                        table[i] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.ALL[m], namer.word(random, true), DescriptiveColor.unevenMix(lifeColorOklab, 4 * lifeAmount, liquidColorOklab, m + 1, DescriptiveColor.BLACK, m));
                    }
                }
                table[36] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.COAST, namer.word(random, true), DescriptiveColor.unevenMix(barrenColorOklab, 1, DescriptiveColor.GRAY, 2));
                table[42] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.RIVER, namer.word(random, true), DescriptiveColor.unevenMix(barrenColorOklab, 2, liquidColorOklab, 4, DescriptiveColor.WHITE, 2));
                table[48] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.LAKE, namer.word(random, true), DescriptiveColor.unevenMix(barrenColorOklab, 2, liquidColorOklab, 5, DescriptiveColor.WHITE, 2));
                table[54] = new Biome(Biome.Heat.COLDEST, Biome.Moisture.OCEAN, namer.word(random, true), DescriptiveColor.unevenMix(barrenColorOklab, 1, liquidColorOklab, 6));
                String hotDesert = namer.word(random, true);
                for (int m = liquidAmount + 1; m < 6; m++) {
                    for (int h = 1; h < 6; h++) {
                        int i = m * 6 + h;
                        table[i] = new Biome(Biome.Heat.ALL[h], Biome.Moisture.ALL[m], hotDesert, DescriptiveColor.unevenMix(barrenColorOklab, 30, liquidColorOklab, m + 1, DescriptiveColor.ORANGE, h + 1));
                    }
                }
                if(lifeAmount <= 0){
                    for (int m = 0; m <= liquidAmount; m++) {
                        for (int h = 1; h < 6; h++) {
                            int i = m * 6 + h;
                            table[i] = new Biome(Biome.Heat.ALL[h], Biome.Moisture.ALL[m], namer.word(random, true), DescriptiveColor.unevenMix(barrenColorOklab, m, liquidColorOklab, m + 1, DescriptiveColor.BLACK, 2, DescriptiveColor.ORANGE, h + 1));
                        }
                    }
                } else {
                    for (int m = 0; m <= liquidAmount; m++) {
                        for (int h = 1; h < 6; h++) {
                            int i = m * 6 + h;
                            table[i] = new Biome(Biome.Heat.ALL[h], Biome.Moisture.ALL[m], namer.word(random, true), DescriptiveColor.unevenMix(lifeColorOklab, 3 * lifeAmount + m, liquidColorOklab, m + 1, DescriptiveColor.BLACK, 2, DescriptiveColor.ORANGE, h + 1));
                        }
                    }

                }
                String coast = namer.word(random, true);
                for (int h = 1; h < 6; h++) {
                    int i = 36 + h;
                    table[i] = new Biome(Biome.Heat.ALL[h], Biome.Moisture.COAST, coast, DescriptiveColor.unevenMix(barrenColorOklab, 20, DescriptiveColor.APRICOT, h + 3, DescriptiveColor.BUTTER, 2));
                }
                for (int m = 7; m < 10; m++) {
                    String name = namer.word(random, true);
                    for (int h = 1; h < 6; h++) {
                        int i = m * 6 + h;
                        table[i] = new Biome(Biome.Heat.ALL[h], Biome.Moisture.ALL[m], name, DescriptiveColor.unevenMix(barrenColorOklab, 1, liquidColorOklab, m - 3));
                    }
                }
                break;
            }
            default:
                System.arraycopy(Biome.TABLE, 0, table, 0, 60);
        }
        return table;
    }
}
